name: Upload Release Assets

on:
  release:
    types: [published]

jobs:
  cosmo:
    name: Cosmopolitan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Setup python
        run: uv python install

      - name: Install depedencies
        run: uv sync --all-extras --dev

      - name: Build executable
        run: ds cosmo

      - name: Upload to release
        run: gh release upload ${{ github.event.release.tag_name }} dist/* --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
